### ISSUE TITLE
"Missing atom fragment" warning for atoms/fragments that are listed in the chemical component dictionary.

### ISSUE THREAD

**Issue by dargen3** [biotite-dev/hydride#18]
Hello,
I've encountered some strange behavior. When I tried to protonate a structure from the PDB database [3u5s](https://www.rcsb.org/structure/3u5s). Hydride wrote out:

/home/dargen3/miniconda3/lib/python3.11/site-packages/hydride/fragments.py:212: UserWarning: Missing fragment for atom 'SE' at position 12
  warnings.warn(
/home/dargen3/miniconda3/lib/python3.11/site-packages/hydride/fragments.py:212: UserWarning: Missing fragment for atom 'SE' at position 136
  warnings.warn(
/home/dargen3/miniconda3/lib/python3.11/site-packages/hydride/fragments.py:212: UserWarning: Missing fragment for atom 'SE' at position 416
  warnings.warn(
/home/dargen3/miniconda3/lib/python3.11/site-packages/hydride/fragments.py:212: UserWarning: Missing fragment for atom 'SE' at position 528
  warnings.warn(
/home/dargen3/miniconda3/lib/python3.11/site-packages/hydride/fragments.py:212: UserWarning: Missing fragment for atom 'SE' at position 552
  warnings.warn(
/home/dargen3/miniconda3/lib/python3.11/site-packages/hydride/fragments.py:212: UserWarning: Missing fragment for atom 'SE' at position 771
  warnings.warn(
/home/dargen3/miniconda3/lib/python3.11/site-packages/hydride/fragments.py:212: UserWarning: Missing fragment for atom 'SE' at position 912
  warnings.warn(
/home/dargen3/miniconda3/lib/python3.11/site-packages/hydride/fragments.py:212: UserWarning: Missing fragment for atom 'SE' at position 1046
  warnings.warn(

while residues with selenium atoms are present in the CCD dictionary and so their fragments should already be in the database. Is this the expected behavior, please?

**Comment by padix-key** [comment]
Hi, I am not able to reproduce these warnings. Can you post the code and both, the Hydride and Biotite version you are using?

**Comment by dargen3** [comment]
Interesting. I couldn't reproduce it today either. Closing. If I come across the error again, I will reopen.
