### ISSUE TITLE
Fragments are not matched if elements are not upper case

### ISSUE THREAD

**Issue by padix-key** [biotite-dev/hydride#20]
As discussed in #19 Hydride does not find a matching fragment if the element in the structure is not upper case.

**Comment by dargen3** [comment]
Hello,

is there any estimation of when this might be fixed? I'm only asking to know if I should write a temporary fix in my workflow or if I can wait for a fix directly in hydrid.

Have a nice day and thank you!

**Comment by padix-key** [comment]
I created a fix. Expect an updated Hydride version in a few days

**Comment by dargen3** [comment]
Amazing! I would also like to ask if there could be a new version of biotite? So I can delete fixes in my workflow to the issue [issue 658](https://github.com/biotite-dev/biotite/issues/658).

**Comment by padix-key** [comment]
I plan to release a new Biotite version within the next two weeks. There are still a few open PRs I would like to merge before, but all of them are close to being ready.

**Comment by dargen3** [comment]
Super, thank you!
